import React from 'react'

export const metadata = {
  title: "Authenticate User",
  description: "Generated by create next app",
};

const Authlayout = ({children}) => {
  return (
    <div className='flex-1 flex items-center justify-center'>{children}</div>
  )
}

export default Authlayout